const SAFE_MESSAGES: Record<string, string> = {
  "Email already registered": "Email already registered",
  "Phone number already registered": "Phone number already registered",
  "Invalid email or password": "Invalid email or password",
  "Invalid OTP": "Invalid OTP",
  "Invalid or expired OTP": "Invalid or expired OTP",
  "Invalid or expired reset token": "Invalid or expired reset token",
  "Invalid role": "Invalid role",
  "Account suspended": "Your account has been suspended. Please contact support.",
  "Access denied. Admin account required.": "Access denied. Admin account required.",
  "User not found": "User not found",
  "Account not eligible for verification": "Account is not eligible for verification",
  "User is not pending verification": "User is not pending verification",
  "Only rejected accounts can resubmit verification": "Only rejected accounts can resubmit verification",
  "Insufficient permissions": "Insufficient permissions",
  "User is not a MED user": "User is not a MED user",
  // Profile update
  "Full name is required": "Full name is required",
  "Invalid phone number format": "Invalid phone number format",
  // Change password
  "Current password is incorrect": "Current password is incorrect",
  // Appointment errors
  "Appointment date must be in the future": "Appointment date must be in the future.",
  "Appointment date and time must be in the future": "Choose an appointment date and time in the future.",
  "Appointment time zone is invalid": "Choose a valid appointment time zone.",
  "Appointment date must be a valid calendar date": "Choose a valid calendar date.",
  "Appointment time must be valid": "Choose a valid appointment time.",
  "Future appointments cannot be marked as completed": "This appointment cannot be completed before its scheduled time.",
  "This date is no longer available. Please select another date.": "This date is no longer available. Please select another date.",
  "You already have an appointment request for this date.": "You already have an appointment request for this date.",
  "Appointment not found": "Appointment not found.",
  "Only pending appointments can be approved": "This appointment can no longer be approved.",
  "Only pending appointments can be rejected": "This appointment can no longer be rejected.",
  "Only approved appointments can be marked as completed": "Only approved appointments can be marked as completed.",
  // B&A
  "Entry not found": "Entry not found.",
  "Contest entry not found": "Contest entry not found.",
  "Closed contest entries cannot be deleted": "This contest week has closed, so its entry can no longer be deleted.",
  "Voting has closed for this contest week": "Voting has closed for this contest week.",
  "Invalid contest week": "Choose a valid contest week.",
  "This contest week is still open": "The winner cannot be resolved until this week ends.",
  "This week has no unresolved tie": "This week has no unresolved tie.",
  "Choose one of the tied top-voted entries": "Choose one of the tied top-voted entries.",
  "This tie was already resolved": "This tie was already resolved. Refresh the list.",
  "Title is required": "Title is required.",
  "Description is required": "Description is required.",
  // Training enrollment & payment
  "Training not found": "Training not found.",
  "Training is not available for enrollment": "This training is not available for enrollment.",
  "Training is full": "This training is full. No more slots available.",
  "This training is full. No more slots available.": "This training is full. No more slots available.",
  "Submit the training application before payment": "Submit the training application before payment.",
  "Discount code is invalid or no longer available": "This discount code is invalid or no longer available.",
  "Emergency details and a supporting document are required to waive a late-cancellation penalty": "Emergency details and a supporting document are required for a late-cancellation waiver.",
  "Observer enrollment is only available when enrollee seats are full": "Observer enrollment is only available when enrollee seats are full.",
  "Already enrolled in this training": "You are already enrolled in this training.",
  "Registration for this training was cancelled": "This registration was cancelled. Please choose another training session.",
  "You must complete a Mint Lift Group Training or Supplemental training first": "You must complete a Mint Lift Group Training or Supplemental training first.",
  "Enrollment not found": "Enrollment not found.",
  "Active paid enrollment not found": "An active paid enrollment was not found.",
  "Cancellation reason is required": "Please provide a cancellation reason.",
  "Reschedule reason is required": "Please provide a reschedule reason.",
  "A replacement training is required": "Please select a replacement training.",
  "Select a different training": "Please select a different training.",
  "Completed or no-show training cannot be cancelled": "A completed or no-show training cannot be cancelled.",
  "Training has already started and can no longer be changed": "Training changes are no longer available after the training has started.",
  "Cancelled enrollment cannot be completed": "A cancelled enrollment cannot be completed.",
  "A training change request is already pending": "You already have a pending training change request.",
  "Reschedule requests must be submitted at least 10 business days before training": "Reschedule requests must be submitted at least 10 business days before training.",
  "Replacement training is unavailable": "The selected replacement training is unavailable.",
  "Replacement training must use the same training level": "Please select a replacement with the same training level.",
  "Replacement training must be upcoming": "Please select an upcoming replacement training.",
  "You already have an enrollment for the replacement training": "You already have an enrollment for the selected replacement training.",
  "You already have an application for the replacement training": "You already have an application for the selected replacement training.",
  "You already have a registration for the replacement training": "You already have a registration for the selected replacement training.",
  "Training change request not found": "Training change request not found.",
  "Training change request was already reviewed": "This training change request was already reviewed.",
  "Reschedule request not found": "Reschedule request not found.",
  "Reschedule fee must be paid before approval is completed": "The reschedule fee must be paid before the change is finalized.",
  "Replacement training is full": "The selected replacement training is full.",
  "Replacement training became unavailable and the reschedule fee was refunded": "The replacement session is unavailable. Your reschedule fee was refunded and your original enrollment remains in place.",
  "Training date is not configured": "The training date is not configured.",
  "Training payment was not found": "The original training payment was not found.",
  "Payable reschedule request not found": "A payable reschedule request was not found.",
  "Reschedule payment not found": "The reschedule payment was not found.",
  "Reschedule fee payment has not succeeded": "The reschedule fee payment has not succeeded.",
  "Reschedule fee payment is processing": "Your reschedule payment is still processing. Please check again shortly.",
  "Observer cannot be marked as a trainee no-show": "Observers cannot be marked as trainee no-shows.",
  "Only paid enrollments can be marked no-show": "Only paid enrollments can be marked as no-shows.",
  "No-show cannot be recorded before the final session": "A no-show cannot be recorded before the final training session.",
  "Attendance was already finalized": "Attendance was already finalized.",
  "No-show fee not found": "A payable no-show fee was not found.",
  "No-show payment not found": "The no-show payment was not found.",
  "No-show fee payment has not succeeded": "The no-show fee payment has not succeeded.",
  "No-show fee payment is processing": "The no-show fee payment is still processing. Please check again shortly.",
  // Training cancellation
  "Training is already cancelled or completed": "This training is already cancelled or completed.",
  "Completed training sessions cannot be cancelled": "Completed training sessions cannot be cancelled.",
  "Training can only be cancelled when there is exactly 1 paid enrollee and no observers": "Training can only be cancelled when there is exactly 1 paid enrollee and no observers.",
  "No payment found for this enrollment": "No payment record found for this enrollment.",
  // Sales rep
  "A user with that email or phone number already exists": "A user with that email or phone number already exists.",
  // Documents
  "Folder not found": "Folder not found.",
  "Document not found": "Document not found.",
  "Parent folder not found": "Parent folder not found.",
  // Commerce
  "Product not found": "Product not found.",
  "Variant not found": "Product variant not found.",
  "Price is required": "Enter a price before saving.",
  "Enter a positive price in USD with no more than two decimals": "Enter a positive USD price with at most two decimal places.",
  "Configure the Stripe product and price before changing its price": "This product needs a linked Stripe product and price before its price can change.",
  "The linked Stripe price does not match this product": "The linked Stripe price does not match this product. No changes were saved.",
  "Unable to sync price with Stripe. No changes were saved": "Could not update Stripe pricing. No changes were saved.",
  "Product price changed. Refresh and try again": "Product pricing changed. Refresh and try again.",
  "Change Stripe mapping and product pricing separately": "Save Stripe mapping and price changes separately.",
  "Order not found": "Order not found.",
  "Shipping label not found": "Shipping label not found.",
  "At least one product is required": "At least one product is required.",
  "Product is out of stock": "Product is out of stock.",
  "Product checkout is not configured": "Product checkout is not configured for this item yet.",
  "Shipping address is incomplete": "Please add a complete shipping address before checking out.",
  "Unable to calculate shipping cost": "We couldn't calculate shipping for this order. Please try again shortly.",
  "Unable to generate shipping label": "We couldn't generate a UPS label for this order. Please check the order's shipping address and try again.",
  "Unable to void UPS shipment": "UPS could not void this shipment. The shipping label is still active; please try again.",
  "UPS shipment identifier is missing": "This UPS label is missing its shipment identifier and cannot be voided automatically.",
  "Shipping label cannot be voided": "This shipping label cannot be voided in its current status.",
  "UPS account number is not configured": "UPS shipping is not fully configured yet (missing account number).",
  "UPS shipper phone is not configured": "UPS shipping is not fully configured yet (missing shipper phone number).",
  "No payment found for this order": "No payment found for this order.",
  "Order is not refundable": "This order is not refundable.",
  "Refund amount must be greater than zero": "Refund amount must be greater than zero.",
  "Payment has not succeeded": "Payment has not succeeded.",
  "Payment amount does not match order": "Payment verification failed for this order.",
  "Payment amount does not match enrollment": "Payment verification failed for this enrollment.",
  "Enrollment payment could not be finalized": "Payment was received but enrollment could not be finalized. Please contact support.",
  "Cancelled order cannot be paid": "This order has already been cancelled.",
  "Order payment could not be finalized": "Payment was received but the order could not be finalized. Please contact support.",
  "Order total changed": "The shipping rate changed. Please review the updated order total.",
  "Unable to create order number": "The order could not be numbered. Please try checkout again.",
  "Order must be paid before creating a shipping label": "The order must be paid before creating a shipping label.",
  "Order must be verified before creating a shipping label": "Verify the order before creating a shipping label.",
  "Shipping label cannot be created for this order": "A shipping label cannot be created for this order in its current status.",
  "UPS label generation is already in progress": "UPS label generation is already in progress. Please wait and refresh the order.",
  "Shipping country is invalid": "The shipping country is invalid.",
  "Shipping state is invalid": "The shipping state is invalid.",
  "UPS shipping is currently limited to US addresses": "UPS shipping is currently available only for US addresses.",
  "Unsupported shipping method": "Please choose UPS Ground or UPS 2nd Day Air.",
  "Unsupported UPS shipping method": "This order's shipping method cannot be booked with UPS automatically.",
  "Order must be paid before processing": "The order must be paid before it can be processed.",
  "Order must be paid before verification": "The order must be paid before it can be verified.",
  "Order cannot be verified in its current status": "The order cannot be verified in its current status.",
  "Order must be paid before shipping": "The order must be paid before it can be shipped.",
  "Order must be verified before shipping": "Verify the order before marking it shipped.",
  "Tracking is required before shipping": "Add tracking information before marking the order shipped.",
  "Order cannot be marked as shipped from its current status": "The order cannot be marked shipped from its current status.",
  "Only a shipped order can be marked delivered": "Only a shipped order can be marked delivered.",
  "Order must be paid before adding tracking": "The order must be paid before tracking can be added.",
  "Order must be verified before adding tracking": "Verify the order before adding tracking.",
  "Tracking cannot be changed for this order": "Tracking cannot be changed for this order.",
  "Cancelled order status cannot be changed": "A cancelled order's status cannot be changed.",
  "Shipped or delivered orders cannot be cancelled": "Shipped or delivered orders cannot be cancelled.",
  "Void the shipping label before cancelling this order": "Void the active shipping label before cancelling this order.",
  "Order cancellation could not be approved": "This cancellation request changed. Refresh the order and try again.",
  "Product variant not found": "The selected product variant is no longer available.",
  "Invalid order status": "Choose a valid order status.",
  "Use the cancellation route to cancel and refund an order": "Use the cancellation action to cancel and refund an order.",
  "Only paid orders can advance through fulfillment": "Only paid orders can advance through fulfillment.",
  "Delivered order status cannot be changed": "Delivered orders cannot return to an earlier status.",
  "Order cannot return to processing from its current status": "This order cannot return to processing.",
  "Order cannot return to pending from its current status": "This order cannot return to pending.",
  "Order status is required": "Choose an order status.",
  "Use the verification route to verify an order": "Use the verification action to verify an order.",
  "Fulfillment and delivery statuses are managed by the order status": "Change the order status to update fulfillment and delivery.",
  "Invalid fulfillment or delivery status for a shipped order": "The shipping fields do not match a shipped order.",
  "Invalid fulfillment or delivery status for a delivered order": "The delivery fields do not match a delivered order.",
  "Delivery status cannot be set through tracking": "Use the order status action to change delivery status.",
  "Tracking number is required": "Enter a tracking number.",
};

const FALLBACK_MESSAGES: Record<string, string> = {
  register: "Registration failed. Please try again.",
  login: "Login failed. Please try again.",
  webLogin: "Login failed. Please try again.",
  forgotPassword: "Request failed. Please try again.",
  verifyOtp: "OTP verification failed. Please try again.",
  resetPassword: "Password reset failed. Please try again.",
  submitVerification: "Verification submission failed. Please try again.",
  resubmitVerification: "Verification resubmission failed. Please try again.",
  approveVerification: "Approval failed. Please try again.",
  rejectVerification: "Rejection failed. Please try again.",
  getPendingVerifications: "Failed to retrieve pending verifications.",
  getMedUsers: "Failed to retrieve MED users.",
  getMedUserById: "Failed to retrieve user details.",
  getVerificationDetail: "Failed to retrieve verification details.",
  // Appointments
  createAppointment: "Failed to submit appointment request. Please try again.",
  getMyAppointments: "Failed to load your appointments.",
  getBlockedDates: "Failed to load availability. Please try again.",
  getAppointmentRequests: "Failed to load appointment requests.",
  approveAppointment: "Failed to approve appointment. Please try again.",
  rejectAppointment: "Failed to reject appointment. Please try again.",
  completeAppointment: "Failed to mark appointment as completed. Please try again.",
  updateProfile: "Failed to update profile. Please try again.",
  updateProfilePicture: "Failed to update profile picture. Please try again.",
  changePassword: "Failed to change password. Please try again.",
  // B&A
  createBAEntry: "Failed to create entry. Please try again.",
  getMyBAEntries: "Failed to load entries.",
  getMyBAEntryById: "Failed to load entry details.",
  deleteBAEntry: "Failed to delete entry. Please try again.",
  getBAEntryCount: "Failed to load entry count.",
  createContestEntry: "Failed to submit contest entry. Please try again.",
  getMyContestEntries: "Failed to load contest entries.",
  getMyContestEntryById: "Failed to load contest entry details.",
  deleteContestEntry: "Failed to delete contest entry. Please try again.",
  getAllBAEntries: "Failed to load B&A entries.",
  getBAEntryByIdAdmin: "Failed to load entry details.",
  getAllContestEntries: "Failed to load contest entries.",
  getContestEntryByIdAdmin: "Failed to load contest entry details.",
  toggleContestLike: "Failed to update like. Please try again.",
  resolveContestTie: "Failed to resolve the contest tie. Please try again.",
  getBAStats: "Failed to load B&A statistics.",
  // Training payment
  createPaymentIntent: "Failed to initiate payment. Please try again.",
  confirmPayment: "Failed to confirm payment. Please try again.",
  // Sales rep
  getTransactions: "Failed to load transactions.",
  getEnrollees: "Failed to load enrollees.",
  listSalesReps: "Failed to load sales representatives.",
  createSalesRep: "Failed to create sales rep account. Please try again.",
  // Training documents
  getFolders: "Failed to load folders.",
  createFolder: "Failed to create folder. Please try again.",
  uploadDocument: "Failed to upload document. Please try again.",
  deleteFolder: "Failed to delete folder. Please try again.",
  deleteDocument: "Failed to delete document. Please try again.",
  // Commerce
  getCommerceDashboard: "Failed to load commerce dashboard.",
  getCommerceProducts: "Failed to load products.",
  getCommerceProductById: "Failed to load product.",
  updateCommerceProduct: "Failed to update product.",
  updateCommerceProductVariantPrice: "Failed to update variant price.",
  getLowStockProducts: "Failed to load low stock products.",
  getCommerceOrders: "Failed to load orders.",
  getCommerceOrderById: "Failed to load order.",
  updateCommerceOrder: "Failed to update order.",
  refundCommerceOrder: "Failed to refund order.",
  getCommerceCustomers: "Failed to load customers.",
  getCommerceCustomerById: "Failed to load customer.",
  getCommerceReports: "Failed to load commerce reports.",
  getShippingLabels: "Failed to load shipping labels.",
  getShippingLabelById: "Failed to load shipping label.",
  createShippingLabel: "Failed to create shipping label.",
  generateUpsShippingLabel: "Failed to generate UPS shipping label.",
  updateShippingLabel: "Failed to update shipping label.",
  createProductOrderIntent: "Failed to create product payment intent.",
  confirmProductOrderPayment: "Failed to confirm product order payment.",
  getMyCommerceOrders: "Failed to load your orders.",
  getProductCheckoutProfile: "Failed to load your shipping address.",
  quoteProductOrder: "Failed to calculate your order total.",
};

export function sanitizeError(error: unknown, operation: string): string {
  if (error instanceof Error) {
    // Only return the message if it's in our safe list
    if (SAFE_MESSAGES[error.message]) {
      return SAFE_MESSAGES[error.message];
    }

    // Pass through dynamic messages that are safe to show users
    if (
      error.message.startsWith("You need at least") ||
      error.message.startsWith("You must complete") ||
      /^Only \d+ available for /.test(error.message)
    ) {
      return error.message;
    }

    // Log the actual error for debugging (internal only)
    console.error(`[${operation}] Internal error:`, error.message);
  } else {
    console.error(`[${operation}] Unknown error:`, error);
  }

  // Return generic message for anything else
  return FALLBACK_MESSAGES[operation] ?? "Something went wrong. Please try again.";
}
